Update English RefCard to Pd 0.49.1
kbarkati/Pure-Data-Refcards pull request #1
Opened 2018-11-09 15:30 UTC by NiccoloGranieri

Updated english refcard to Pd 0.49.1 adding new objects, and doing minor corrections to the object descriptions.

2018-11-13 13:26 UTC, kbarkati requested changes
Thank you Niccolo for your contribution. It is more complete and still compiles nicely, on a single page.

I have two changes requests before approving your pull request:
1. the copyright time span
2. the Italian translation

2018-11-13 13:26 UTC, kbarkati commented on pd-refcard-en.tex
> +    \tiny{Copyright \copyright{2018} Karim \textsc{Barkati} <\email{karim.barkati@gmail.com}> \& Niccolò \textsc{Granieri} <\email{granieriniccolo@gmail.com}>. Permission is granted to copy, distribu
I just would indicate the whole time span of the copyright, in order to let people know when the refcard started:

```
\copyright{2010-2018}
```

2018-11-13 13:26 UTC, kbarkati commented on pd-refcard-it.tex
> +    bang & output a bang message \\
An Italian translation is welcome but the source code I can see here is still in English.

2018-11-13 14:49 UTC, NiccoloGranieri commented on pd-refcard-en.tex
> +    \tiny{Copyright \copyright{2018} Karim \textsc{Barkati} <\email{karim.barkati@gmail.com}> \& Niccolò \textsc{Granieri} <\email{granieriniccolo@gmail.com}>. Permission is granted to copy, distribu
I'm totally fine regarding the extension of the time span.

2018-11-13 14:50 UTC, NiccoloGranieri commented on pd-refcard-it.tex
> +    bang & output a bang message \\
I didn't do a pull request for the italian translation... I thought I kept that on my private repo until I had time to work on it! Sorry for that.

2018-11-13 14:51 UTC, NiccoloGranieri commented
I have never worked with change requests on pull requests. How does it work? Do I need to make the changes on my repo and submit a new pull request?

2018-11-13 15:07 UTC, kbarkati commented
> I have never worked with change requests on pull requests. How does it work? Do I need to make the changes on my repo and submit a new pull request?

You just have to push new commits that fix the change requests. No new pull request is needed.

2018-11-13 16:24 UTC, NiccoloGranieri commented
All done!

2018-11-13 16:36 UTC, merged

2018-11-14 10:51 UTC, NiccoloGranieri commented
@kbarkati any idea how we can update the pdf also on the puredata.info website?

2018-11-15 09:08 UTC, kbarkati commented
> @kbarkati any idea how we can update the pdf also on the puredata.info website?

I have just done it: see http://puredata.info/docs/manuals/pdrefcards.
Thank you again for the additions 👍